name: 'Build and Release'

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
          releaseName: ${{ startsWith(github.ref, 'refs/tags/') && format('Milky Warp {0}', github.ref_name) || '' }}
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          includeDebug: false

      - name: List build output
        run: |
          echo "=== Release directory ==="
          ls -la src-tauri/target/release/
          echo "=== Bundle directory ==="
          ls -la src-tauri/target/release/bundle/ || echo "No bundle directory"
          if [ -d "src-tauri/target/release/bundle" ]; then
            find src-tauri/target/release/bundle -name "*.exe" -type f
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: milky-warp-windows-portable
          path: |
            src-tauri/target/release/milky-warp.exe
            src-tauri/target/release/bundle/
